#! /bin/bash

#: Title		    : Backup all MySQL Databases
#: Date			    : 2014
#: Author	    	: github.com/vujke
#: Version		  : 2.0
#: Description	: 

DATE=$(date +"%d%m%Y%H%M")

MYSQL=/usr/bin/mysql
MYSQLDUMP=/usr/bin/mysqldump
MYSQL_HOST="localhost"
MYSQL_USERNAME=""
MYSQL_PASSWORD=""
BACKUP_DIR="$HOME/mysqldump"
DATABASE_DIR="$BACKUP_DIR/$DATABASE_NAME"
SQL_FILE="$DATABASE_NAME"
EMAIL="@gmail.com"
TIME=$(date)

DISTRONAME=$(awk -F 'NAME=' '/^NAME=/{gsub(/"/,"",$2); print $2}' /etc/os-release)
DISTROVER=$(awk -F 'VERSION_ID=' '/^VERSION_ID=/{gsub(/"/,"",$2); print $2}' /etc/os-release)
KERNEL_VER=$(hostnamectl | awk '/Kernel:/ {print $3}')
ISA=$(hostnamectl | awk '/Architecture:/ {print $2}')
HOSTNAME=$(hostname)

i=1

# Check if database directory exist
[ ! -d "$BACKUP_DIR" ]  && mkdir -p $BACKUP_DIR

# Delete databases older than 15 days
find $BACKUP_DIR/$DATABASE_NAME* -mtime +15 -exec rm {} \;

# List all databases
# SHOW DATABASES is regular MySQL command that shows all databases
# Command grep -Ev will NOT show defined database(s)
LIST_OF_DATABASES=`$MYSQL --user=$MYSQL_USER -p$MYSQL_PASSWORD -e "SHOW DATABASES;" | grep -Ev "(Database|information_schema|performance_schema|sys|mysql)"`

for DATABASE_NAME in $LIST_OF_DATABASES; do
  $MYSQLDUMP --force --opt --user=$MYSQL_USER -p$MYSQL_PASSWORD --databases $DATABASE_NAME --skip-lock-tables > ${BACKUP_DIR}/${DATABASE_NAME}_${DATE}.sql
  # Compress every database
  gzip -q $BACKUP_DIR/*
done

for file in $BACKUP_DIR/*$DATE* ; do
  [[ -f "${file}" ]] || continue
  ATTACHMENT+=( "-a" "${file}" )
done

echo -e "List of databases ($(wc -l <<< "$LIST_OF_DATABASES")):\n$(for LIST_OF_DATABASES in $LIST_OF_DATABASES; do
    printf "%d. %s\n" "$i" "$LIST_OF_DATABASES"
    ((i++))
done)
\nSent on $TIME from ${DISTRONAME} v${DISTROVER}; kernel v${KERNEL_VER} @ ${ISA}; hostname: ${HOSTNAME}." "\n\nSee attachment below:" | mailx ${ATTACHMENT[@]} -s "MySQL back up at @${HOSTNAME}" $EMAIL 
